import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from '@/Provider';
import { config } from '@fortawesome/fontawesome-svg-core';
import IconProvider from './components/IconProvider';
import Sidebar from './components/Sidebar';
import ReactQueryProvider from './components/QueryClientProvider';
config.autoAddCss = false; /* eslint-disable import/first */

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="" data-theme="cupcake">
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
				<link
					href="https://fonts.googleapis.com/css2?family=Raleway:wght@600;700&display=swap"
					rel="stylesheet"
				/>

				<link
					href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body className="bg-base">
				<ReactQueryProvider>
					<IconProvider>
						<Provider>
							<div className="flex  h-full min-h-screen duration-1000 transition-all">
								<Sidebar />
								<div className=" w-full overflow-x-hidden">{children}</div>
							</div>
						</Provider>
					</IconProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
